import Navbar from './components/navbar'
// import './globals.css'
// import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Script from "next/script";

// import 'bootstrap/js/dist/bootstrap.min.js'


// const DynamicBootstrap = dynamic(
//   () => require('bootstrap/dist/js/bootstrap.min.js'),
//   { ssr: false }
// );

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {

  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"/>
      </Head>
      <body>
        <Navbar />
        {children}

        <footer>Footer</footer>

        {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"/> */}
   
      </body>
    </html>
  )
}
